name: expro_archives
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.1
  uuid: ^4.3.3 
  firebase_core: ^3.6.0
  cloud_firestore: 5.6.12
  firebase_storage: 12.4.10
   
 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
