name: expro_archives
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.1
  intl: ^0.18.1
  uuid: ^4.3.3 

  # Firebase packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # Supabase
  supabase_flutter: ^2.5.4
  path: ^1.8.0

  # File picker (استخدم آخر إصدار)
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
