// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CSStcCSbdTWkBXouIH2wq46gVQaugjo',
    appId: '1:843782203234:web:42f93b87c08b96822fee3b',
    messagingSenderId: '843782203234',
    projectId: 'exproarcheive',
    authDomain: 'exproarcheive.firebaseapp.com',
    storageBucket: 'exproarcheive.firebasestorage.app',
    measurementId: 'G-X81WRS3HWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1todp813iHYco6Lpy_ersh9hdUERUdno',
    appId: '1:843782203234:android:2ef6cfa56bc90aaf2fee3b',
    messagingSenderId: '843782203234',
    projectId: 'exproarcheive',
    storageBucket: 'exproarcheive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC33u5Ua4TzizZcPQCOCWMKowEH1ypp8PA',
    appId: '1:843782203234:ios:6e18797feee95ae32fee3b',
    messagingSenderId: '843782203234',
    projectId: 'exproarcheive',
    storageBucket: 'exproarcheive.firebasestorage.app',
    iosBundleId: 'com.example.exproArchives',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC33u5Ua4TzizZcPQCOCWMKowEH1ypp8PA',
    appId: '1:843782203234:ios:6e18797feee95ae32fee3b',
    messagingSenderId: '843782203234',
    projectId: 'exproarcheive',
    storageBucket: 'exproarcheive.firebasestorage.app',
    iosBundleId: 'com.example.exproArchives',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5CSStcCSbdTWkBXouIH2wq46gVQaugjo',
    appId: '1:843782203234:web:6b2461626ce08adf2fee3b',
    messagingSenderId: '843782203234',
    projectId: 'exproarcheive',
    authDomain: 'exproarcheive.firebaseapp.com',
    storageBucket: 'exproarcheive.firebasestorage.app',
    measurementId: 'G-PF7HTZQTPG',
  );
}
